version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment: 
      - PORT=3000
      - MONGO_USER=yoniivan
      - MONGO_PASSWORD=pico288
  
  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=yoniivan
      - MONGO_INITDB_ROOT_PASSWORD=pico1288
    volumes: 
      - mongo-db:/data/db

volumes: 
  mongo-db:

